################################
# Site Settings
################################
lang        : "en"
logo        : /assets/img/logo.png
title       : Undergraduate Mathematics Deadlines Calendar


################################
# Theme Settings
################################

theme: jekyll-theme-minimal
show_downloads: false
