################################
# Site Settings
################################
lang        : "en"
logo        : /assets/img/logo.png
title       : Mathematics Deadlines Calendar
description : This list contains an overview of external deadlines for undergraduate mathematics and statistics students.

################################
# Theme Settings
################################

theme       : jekyll-theme-minimal
permalink   : /:title/
show_downloads : false
