################################
# Site Settings
################################
lang        : "en"
logo        : /assets/img/logo.png
title       : UG Mathematics Deadlines Calendar
description : This list contains an overview of external deadlines for undergraduate mathematics and statistics students.


################################
# Theme Settings
################################

theme: jekyll-theme-minimal
show_downloads: false
