################################
# Site Settings
################################
lang        : "en"
logo        : /assets/img/logo.png
title       : Undergraduate Mathematics Deadlines Calendar


################################
# Theme Settings
################################

theme: jekyll-theme-minimal
permalink   : /:title/
logo:
show_downloads: false

# Navigation Menus
header_navigation:
  - title: Notes
    url: /notes/

  - title: Contact
    url: mailto:you@example.com
